parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Cartbot:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Cartbot/Infrastructure/Entity'
                prefix: Cartbot\Domain
                alias: Cartbot
            CartbotPrivate:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/CartbotPrivate/Infrastructure/Entity'
                prefix: CartbotPrivate\Infrastructure\Entity
                alias: CartbotPrivate

