Cartbot\Domain\User\UserChat:
    type: entity
    repositoryClass: Cartbot\Infrastructure\Repository\DoctrineUserChatRepository
    table: userChat

    id:
        id:
            type: string
            nullable: false
            length: 100
            options:
                unsigned: true
            id: true
            column: iduserChat
        type:
            type: string
            nullable: false
            length: null
            options:
                fixed: false

    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idUser:
                    referencedColumnName: idUser
                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }
